# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/


# Site
title: Android 沉思录
subtitle: It's my Androad
description: It's my Androad
author: yeungeek
email: yeungeek@gmail.com
language: zh_CN


# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yeungeek.com
root: /
permalink: :year/:month/:day/:title/
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
permalink_defaults:



# Directory
source_dir: source
public_dir: public


# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
highlight:
  enable: true
  line_number: true
  tab_replace:


# Category & Tag
default_category: uncategorized
category_map:
tag_map:


# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 2
category: 2
tag: 2


# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
server_ip: 0.0.0.0
logger: false
logger_format: dev


# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMM D YYYY
time_format: H:mm:ss


# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page


# Disqus
disqus_shortname:


#plugins
feed:
    type: atom
    path: atom.xml
    limit: 20


# Extensions
## Plugins: https://github.com/hexojs/hexo/wiki/Plugins
## Themes: https://github.com/hexojs/hexo/wiki/Themes
theme: next
exclude_generator:


# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:yeungeek/yeungeek.github.com.git
  branch: master
  message: "yeungeek update site"

# =============================================================================
# NexT Theme configuration
# =============================================================================
swiftype_key: syzrqq5Ho6DDncz_gsad
# 多说帐号
duoshuo_shortname: yeungeek

# DISQUS 帐号 （如果已经设置 多说 帐号，此选项将被跳过）
#disqus_shortname: your-disqus-shortname


# 社交链接，将在侧栏中显示
social:
  GitHub: https://github.com/yeungeek
  Twitter: https://twitter.com/yeungeek
  Weibo: http://weibo.com/springyounger
  #DouBan: your-douban-url
  ZhiHu: http://www.zhihu.com/people/Yeungeek
  # 等等


# Creative Commons 4.0 International License.
# http://creativecommons.org/
# Available: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
creative_commons: by-nc-sa


# Google 站长工具验证，请选择 `HTML Meta` 验证方式
# See: https://www.google.com/webmasters/
#google_site_verification: VvyjvVXcJQa0QklHipu6pwm2PJGnnchIqX7s5JbbT_0


# Google 分析 ID
#google_analytics:


# 百度统计 ID，此 ID 是百度统计提供脚本中 hm.js? 后面那串字符，非百度统计帐号
baidu_analytics: 75ae37defe17129870bc1ba88b527367

# 站点起始时间
since: 2014

# =============================================================================
# End NexT Theme configuration
# =============================================================================
