menu:
  Home: /
  Android每周主题: /categories/Android每周主题
  大牛博客: /android开发大牛博客
  Archives: /archives
  About: /about

widgets: 
- search
- category
- tagcloud
- blogroll

excerpt_link: Read More

twitter:
  username: 
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: false
  twitter: false
  google: false
  pinterest: false
  alimama: true

fancybox: true

google_analytics:
rss:

weibo: true
