menu:
  Home: /
  Android每周主题: /categories/Android/Android每周主题
  Archives: /archives
  About: /about

widgets: 
- search
- category
- tag

excerpt_link: Read More

twitter:
  username: 
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: false
  twitter: false
  google: false
  pinterest: false

fancybox: true

google_analytics:
rss:

weibo: true