menu:
  Home: /
  Archives: /archives
  About: /about

widgets: 
- search
- category
- tag
- twitter

excerpt_link: Read More

twitter:
  username: yeungeek
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: false
  twitter: false
  google: false
  pinterest: false

fancybox: true

google_analytics:
rss: